### PR TITLE
GPII-1707: Fix the version of `simplesmtp`...

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-1707](https://issues.gpii.net/browse/GPII-1707) for details.

### CODE REVIEW

**Comment by amb26** [comment]
Second set of tests fail for me:

14:35:56.468:  jq: Test concluded - Test name "Testing the correct transmission of a mail message by the mailer...": 5/5
 passed - PASS
14:35:56.522:  Starting test mail server on port 4425....
14:35:56.531:  Stopped mail server...
14:35:56.536:  Mail server ready...
14:35:56.560:  jq: FAIL: Test name "Testing the correct receipt of a mail message by the server..." - Message: The messa
ge should contain data that matches the expected 'subject' field... - at sequence position 4 of 5
14:35:56.569:  jq: Source:     at pok (E:\source\gits\gpii-mail-test\node_modules\infusion\tests\test-core\jqUnit\js\jqU
nit.js:110:15)
    at Object.jsUnitCompat.assertTrue (E:\source\gits\gpii-mail-test\node_modules\infusion\tests\test-core\jqUnit\js\jqU
nit.js:143:13)
    at E:\source\gits\gpii-mail-test\tests\lib\caseholder.js:29:20

While we are here, it would be a good opportunity to give this package a useful README file and at least minimal docs - Cheers

**Comment by amb26** [comment]
node 4.2.2, npm 2.14.8 Windows 7 x64

**Comment by the-t-in-rtf** [comment]
I see two intermittent failures inspecting the same mail message on Windows.  Working on it now.

**Comment by the-t-in-rtf** [comment]
On Windows the failures only happen now and again.  I can't reproduce on OS X even running the tests 100 times in a row as quickly as possible.

**Comment by the-t-in-rtf** [comment]
I ran the tests 100 times in a row from Windows Powershell using a command like:

```
For ($i=0; $i -le 10; $i++) {
  npm test > $null | Write-Output
  if (-not $?) {
    echo "FAIL"
  }
}
```

It fails roughly 10% of the time.  With this I can reproduce the problem well enough to try a few things.  I am currently researching the way in which we close a stream and save the local message file to ensure that there isn't an asynchronous call that occasionally fails to complete in time.

**Comment by the-t-in-rtf** [comment]
As I suspected, I needed to ensure that the message file was completely written before firing the `onMessageReceived` event.  I am running a few hundred passes on Windows, thus far I have not seen any further errors after the fix.

**Comment by the-t-in-rtf** [comment]
To protect against a regression on the above, we have agreed to run the tests 25 times (which completes in roughly a minute).

**Comment by the-t-in-rtf** [comment]
I added a caseHolder that duplicates all tests N times, and had it run the tests 100 times for good measure.  I also removed some local cruft that duplicates work in `gpii-express`.

**Comment by amb26** [comment]
Thanks, this branch now works fine. Please remember to take care to run the linting tasks before a commit, I fixed a couple up for you - cheers.

**Comment by the-t-in-rtf** [comment]
@amb26, my apologies, I usually use my IDE to check for lint errors and yet again missed something.

To atone for my sins, I have set things up so that I can't commit in any of my projects if `grunt lint` fails (see the list for details).

**Pull request merged**
